export const PROJECT_FORM = 'PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ERROR_NEW_PROJECT_FORM = 'ERROR_NEW_PROJECT_FORM';
export const GET_SELECTED_PROJECT = 'GET_SELECTED_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const GET_PROJECT_TASKS = 'GET_PROJECT_TASKS';
export const ERROR_NEW_AND_EDIT_TASK_FORM = 'ERROR_NEW_AND_EDIT_TASK_FORM';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';